language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
env:
  global:
  - secure: keUCJEqG6ctYsGdMpNeZEXCgRMaJeRo1s4xMP8zeVUN3vyOkLBmK8tVqwTwgStjjNyYn9g5FgtB++ofRv21TF8s3dGxCQcuV4ru5DbndNbhzwDRv//F+5/wtAP1LWgcBv+epBzQl3HnZJ5JcgrQC1+nLNOwW1KU8O4zO2Qi/TpRWIBagthPGnM2Wck1f+DoTawqyCyJjZ5w3A+fojx0s3KSJLaI7Xx3DfE02FN6G55/F7X++aoxftcL3pxEzC8YdZKRnYgpscH4GUqxJTJ4GFSflGE54GNOgVXY7fq12n3QyGl6SD++jZaDCaHJk5uprCpK+fu5jU/KBzqSI3ZjAqnvzaL9mP6xddh/L16JtLDMWa+/Nkwi7tv7vOaXw4GCtxAr+cNCIKQ7scfrIs0lRfQrFY9ZIbfm5WtlesF5qOEzBTkKO/AA6r1TB0IaOg9ck9exTKiYKFeBsS0XKvwko5q5fdBTYZKYwmH5fnM1s28nIIdvFGaPkET3KCht5C4v8w4c3nSMp7VJ942Gqdx9YGuR4WEJHwaurUGz1DrF6uHuDCIVsVgJfyW9bwYtWyZObDnk6JAySCqSxVAhtL40QAuaJtIdFae3flE+k6PjHeoGmRTvJdaHuN+hPPA6wSReeb4Nce32QILcD9loWXEgKwRKe5+22KsP4yEIKkISsPmA=
  - secure: hxNSmaPerJmKWAqFzeVc9JaRIzrnUVPyg0Rsi0Daqn5a701xm7swWW17X9zIafxyr0C0ZANm0UCKrqasqTjAPBRn12RtawJpwopI20p9tQu7hGsMuO84Dp93oyZMnR5CFv/wol2bqmyYUwd/kQZVZLZ0XuUdQdfeJ5TorxCNy+DNKAz19USiZHBsBm3iDLGezJH9zoaZlovOrdf359SncBuGoqLrxBXJmz+4N6/zLPSEKw8UBieLteLoypEaJ0liUM3nM58oXameZs5oNw80m1zaNNPEQJ5LU68mL9hgN/IEA3i++ZksNj8ftkPD9fFiZiT8vWumh7gib9KrTysn9pSxOclh6fJValIXz5sPhWY5aNnBt+xTauU7vtSZNPVvv/pGiVDKpIyXs5rewmCnc4FvmBzyVC9vGLw8MgSnheBDobNGrXCqeCMQuTPpVnw9WIc/xOnSeRtc3Xq+CsmitlsIarW/OTcXr1NtgBwuFzUpEoitAe9xFpXflbnVjs/1EOxu61rksuy1XPR6XeBfAofjtZ0lhlWA6TrLrRofPwrZsenf8M4xrReiViZiVPWisgZJZaMcEmlEvuKyYJ5E9axyxmr4itTQ0N4PHJO3lrjHgY5D4er1rG8DcBLDyt62qvwLK2xnUeDs0gTtMyMzYfxiroVIY0ZZVvu1KNWEVqg=
  - secure: McPvXfHIgWg5pICZkDwPNahCaLKe5K1i7yQP9p+IqThtl2ugtcw85IgYvLIpxwG0YrsNqGPSA9aHAF+LKZauZOjDsNZd5M6FZBDHZH/uzHWuxkDmieE5PWTlLXqP1cMbbYR1Ub1ew1t2bYJR13D5G53X0B5le3K7CfN7miQasG851MDISggm5xcvfOXsVqEIMZNSF6FA9ViHEW1Kbp6O+H8Qt7qTHu5zsRqL5J4J0czamytuJWNbIqSJ85yWD1vWYCiuB4WsDt5spahsG+Zi6TmAHR3YddRyALoLJmCwWUABM8lm326tJUGTrgOVD/LkJZiXQFDuCZFenjZtuqi5Q9uf6Bq5uBhGk1LFB7fcqHunMG7x7Yyyx13dHXY2JukWrKUrS7OzFmzp2UrdGTUSrVt0Q3F6mTPWL8ffebVP5Jojl7inIW4sL1U/QzbagQZSwIC5s4mKb51g5aLIM3+UfYDlBWL5//0U8kL4BhfCBukOsec1d2oCSA4jOWIm3O4fBuL/niLuN40o4h+lhdCn8tm1VCBz+WDB9R1QwJfun5V+q9eLHuC7m0UCGOGh2/ujyVMaUlQPkYsayJ/JWLcvL+8epSHoC7mDYbJJLr3dme4pHcgm3/VOpn3AEMTi9DlIQCHeg2MlgcJEb0rJ6lot98RLVAlLqrJ7gdSUTA+G2nE=
deploy:
  skip_cleanup: true
  provider: script
  script: rsync -auz -e 'ssh -p ${SCP_PORT} -o "StrictHostKeyChecking no"' -r --delete-after
    --quiet ${TRAVIS_BUILD_DIR}/build/ ${SCP_USER}@${SCP_HOST}:~/www/
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_f522af131703_key -iv $encrypted_f522af131703_iv
  -in deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_key
- ssh-add deploy_key
script:
- yarn test
- yarn build
notifications:
  slack:
    secure: iFyIvd/gGSxM3LJLLH1FhxaYHK/K585SIDK4sM6RccZoIWo6QDF2e4dZzeEwh1kCn8RXpR82yjzBmmVu3189xUZQck2zsL2Ht4rRRAgULP02aguclb2yqCbXsAu5+f6h89d+E4oXcNmvn6pUGcyPhuZRyZBje7qFvkCiNs4nV+BrswXOCqauzUtdiigM6MAeHOC5eg6xwcR8ArvwpLF9Bw3LkFtskSzTiEsqmqAUxg5Q2w1iRxK0BRADj+H/lgwJ9sWTyPsm8k4r/4PtDA4+oon5OotfT1DaDd109NNOqrYm9EJDBgv/wn3S2RNdxZtuHhc6NWZuIYDKdGsmWW3XOagebVHscpUkuzkgDx9cq5jGelzAqalCu8AHN+kNs7KXigEFYkqS8z7bMBACcDOZ5BSTEA3V2BsJcSDfgovjymAK21G+NS2U/le09yVgf1e/GAHfC6r3YedVSwxKL4Ad02Fa+KihP7TwHGR1K6H9uJwAf3e14477X12DEMjynyCH8x1FeWDvn6dWjjLSbnRJ5+QFgVhC4zxO53q52nv7ZZbAgnPFILGWk6ce5YE4eCSGKctqPr9yq9VhtMN9pal83edOqSnNnmtuJ7oeol9TSMJZCPSI8KDRRUhzRS3aCEAfTjiwKqS51Uzhd9ysnwKaE1dDDWRdsAMFgz65FXWT6nQ=
