language: node_js
node_js: '8'
cache:
  directories:
  - node_modules
script:
- yarn test
env:
  global:
  - secure: nGjM3XlS92a5UK19Z0eNmONY7wcDUtr3UQp0CAGG7NXCfIC65qGXI2Vvd712dg6Zmdm8OPsi25PZOk8e9XI7OVwmcSMw0PZ6X0Byf6eUKbwquJhlILyWy8A0WLqMD99Ep5Zm0QoCvchGkq286eNLUjsRlv0w1HpDnDUt+Egg9Rrk4WXRuyvdIgG4UX1qw+spTyH4O9o0r1Cw2AliUBORbV4cColNbiVz1zJrlgUljGWKRSEJ3azRaFLHzgGg/mEMvd1jgZKt3t3cxE73dIZAeWPQcKJNUAc8KX8S5CPwl+f3aXi7AqQ9aRjjBRf2B+tTnNZgWfoDLDIKfOEgTIFfV7jMxpiOKHnDTS0tTP2Wm3E9E5WIHEERLS0DtqHrQhhCKeEi/deMZ7WgAUUmt/TTCr5ft1ONZ+K1Wew42SK9GCcig3MXJZgC3fNos8vWaF3+0uIBUuEa5uU7m/EXLvyNIMeKiZuwVZ59qOgiVXEPiEIBVIRByCcL3OvA9Q1CSFsryzGEe45Zx8oO6IBKPTPXz+LsmYqFP/6I34vm30I/dgUoDUH4bVrMTfV1OJVEN1ERcy1yYcYRs4tIOH7PnK67JCgZNNu9rIlhDXoLILpS7rkFfwz03BepWXk4TOmHKUnxutt+O2HjVjWEdEzQklZuIZHO1F1bvacWQJgLrSNIYoE=
  - secure: XFVvmsT9Da6gapLSt8ZqgMt3Ec4t13wI46dx/Yd1f0oabvC1VQSubqW8Ydu4Vhk+wni4ryFYDojqaKPX4Vfc8a/RlV/59hjuqwZJnl3LpNtKj5z1tSLLdzkp4DFtDAIG+5YM0/cSlanIMneo7h6jTvJn5pInuJvwYYMnZUA3pn7d2SZ/fRuQWI4uRU3L8QBBNJazM98vPhTYASffP3w9pGl3oPC8MMDf1To6YdD2buFsN+365TFScNAMZ0Av4ho44hxGs0GQjE6X4NvIZSuaR6iU6Zdgkw0lsMksTABRg7fwmpxHbaki/sg1BKLhdFKQ+kUnAk/v7J7jXxaV37fna5aFkiDL67/yOuWB/wsqfIyz2sggMtTUH6y8dbNiuPZPT4znTQ61ScCWFExTddLwJb5RilaR2lFQtXoPfOYgxLm2LH/4qYlEcZjTFVvXoFf0fDduZyXIcrpu56AvypwiMZ3EdAj8wRAFopGSWrhSCW6OkMfBQjsONv80Urad7CvKfHgtecWfHjd1CvckH15PPo5bBalSD+c5NAPp1KlPTQMtIr8L0NdSjxyMY5cQv8WivvTE4+jg23uT1CCxLHDJn0k/LB49kO3gRwt6mQxNF7W4zNTMxdx+qH03tvusitb/sJ79UXhMwciXEufwdIjYuyCFXoBUOspe3rnSs0FzAjM=
before_install:
- openssl aes-256-cbc -K $encrypted_684ad3c7c302_key -iv $encrypted_684ad3c7c302_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
after_success:
- echo "${SFTP_KEY}" | base64 --decode >/tmp/sftp_rsa
- curl --ftp-create-dirs
       -T filename
       --key /tmp/sftp_rsa
       sftp://${SFTP_USER}:${SFTP_PASSWORD}@150.95.155.136/srv/www/
